### PR TITLE
Support node versions higher than v12

### LINKED ISSUE #60: [BUG] Support node LTS
As I was trying to install the `@twilio/voice-sdk` I got the following error:

> error @twilio/voice-sdk@2.1.0: The engine "node" is incompatible with this module. Expected version "12". Got "16.6.2"

It would be nice if this package would work with the latest node LTS (v16).

Keep up the good work!

### PR DESCRIPTION
**Pull request by benmccallum**
**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### JIRA link(s):

- [CLIENT-0000](https://issues.corp.twilio.com/browse/CLIENT-0000)

### Description

Fixes #60

### Before review
* [ ] Updated CHANGELOG.md if necessary
* [ ] Added unit tests if necessary
* [ ] Updated affected documentation
* [ ] Verified locally with `npm test`
* [ ] Manually sanity tested running locally
* [ ] Ready for review

### Before merge
* [ ] Got one or more +1s
* [ ] Squashed erroneous commits if necessary
* [ ] Re-tested if necessary

### CODE REVIEW

**Comment by benmccallum** [comment]
Not sure what would be involved from a CI/testing perspective here, but trying to get the ball rolling.

**Comment by ryan-rowland** [comment]
Thanks for the contribution @benmccallum ! This should be a simple one -- let's see what Circle says :)

**Comment by snkashis** [comment]
Any idea when a release with this will be pushed to NPM?

**Comment by BenShaffer** [comment]
I too would like to know when this will be released.

**Pull request merged**
