### PR TITLE
VBLOCKS-1155 Make sure publisher host is inited if home region exists

### PR DESCRIPTION
**Pull request by charliesantos**
This is an updated fix for https://github.com/twilio/twilio-voice.js/pull/121

### CODE REVIEW

**Comment by charliesantos** [comment]
@kamalbennani @rmnbrd can you please take a look at this one and see if it fixes your need? This is in response to your PR https://github.com/twilio/twilio-voice.js/pull/121

You are correct that the publisher's host is not updated after calling updateOptions. However, we need to reinitialize from the home region value.

**Comment by charliesantos** [comment]
> It seems like we only set the `this._home` value when we receive a "signaling connected" message, what happens if the token is updated such that `this._home` doesn't reflect the home region of the new token?

Good call @mhuynh5757 . This won't be an issue because it is not possible to update the token of an existing device with a different region. The SDK will emit an error in this case. The region and edge parameter needs to match in order for this to work. Meaning, in order to update the home region, you also need to reinitialize the device which will in turn reinitialize signaling and the `_home` property.

Reference: https://github.com/twilio/twilio-voice.js/blob/master/CHANGELOG.md#twilio-regional-support

**Comment by kamalbennani** [comment]
This would work perfectly fine I guess, it's pretty much the same as the solution suggested by @rmnbrd.
I have a nitpicky comment (that you could definitely ignore) but it would be very nice to have the `this._host` assignment next to this._region/this._edge in the `signalingConnected` [method](https://github.com/twilio/twilio-voice.js/blob/19bbeea1370946212b66cd1d6ccb12c0e3033b6c/lib/twilio/device.ts#L1108)
Other than that LGTM.

**Comment by kamalbennani** [comment]
And btw, would it be possible to release it as soon as you could please 🙇

**Comment by rmnbrd** [comment]
Hello @charliesantos, 

Indeed, the changes of this PR seem to resolve the issue @kamalbennani and I described in https://github.com/twilio/twilio-voice.js/pull/121

Could you please let us know if you have any ETA for the release of that fix. 
Because as @kamalbennani mentioned, this problem is affecting us a lot right now, so we would like to know whether we should deploy our hotfix (in which we patched your SDK), or wait for a release from your side.
Thank you in advance.

**Review by mhuynh5757 — APPROVED** [review]

**Comment by charliesantos** [comment]
@kamalbennani @rmnbrd thank you for your input. Romain's PR is good, however, it is using default host which will route data to a default region if we publish right before signaling is connected. This is bad from data privacy perspective.

Moving `_home` assignment next to `_edge`/`_region` is a good idea. I will go ahead and update that.

As for ETA, we will proceed with our internal release process. The patch release should be out after 1 day at the earliest if there are no issues found.

**Pull request merged**
