### PR TITLE
fix(socket): throw an error when the socket fails to connect

### PR DESCRIPTION
**Pull request by kamalbennani**
**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### Description

This PR aims to fix the issue described here: https://github.com/twilio/twilio-voice.js/issues/231

### Before review
* [ ] Updated CHANGELOG.md if necessary
* [x] Added unit tests if necessary
* [ ] Updated affected documentation
* [x] Verified locally with `npm test`
* [x] Manually sanity tested running locally
* [x] Ready for review

### Before merge
* [ ] Got one or more +1s
* [x] Squashed erroneous commits if necessary
* [x] Re-tested if necessary

### CODE REVIEW

**Comment by kamalbennani** [comment]
Hi @charliesantos 
Would you mind taking a look at this PR whenever you have time.
Really appreciate it.

**Comment by charliesantos** [comment]
Good find @kamalbennani ! Thanks for submitting. I created an internal ticket to have this reviewed and tested further.

**Comment by kamalbennani** [comment]
Thanks @charliesantos

**Comment by kamalbennani** [comment]
Hi @charliesantos 
Any update on this?
Can we get it release this week if it passes the validation?
Thanks buddy.

**Comment by charliesantos** [comment]
Hi @kamalbennani. It's in our queue. ETA is 1-2 weeks.

**Comment by charliesantos** [comment]
@kamalbennani I submitted a new PR to capture your changes. I also made a few modifications so that handlers are getting cleaned up properly. See it here https://github.com/twilio/twilio-voice.js/pull/236
As always, thank you for your contribution!

**Pull request closed without merging**
